name: AWS SSM Parameters
description: Checks to see if exists, if not it will create it. If exist, it will check to see that is current and up to date.

branding:
  icon: refresh-cw
  color: orange

inputs:
  name: # id of input
    description: AWS SSM Parameter Name
    required: true
  value:
    description: AWS SSM Parameter Value
    required: true
  description:
    description: AWS SSM Parameter Description
    required: true
  tier:
    description: AWS SSM Parameter Tier
    required: false
    default: Standard

runs:
  using: 'composite'
  steps:
    - run: echo "--- Checking AWS SSM Parameters ---"
      shell: bash
    - run: pip3 install boto3
      shell: bash
    - id: ssm-parameters
      run: ${{ github.action_path }}/ssm-parameter.py --name "${{ inputs.name }}" --value "${{ inputs.value }}" --description "${{ inputs.description }}" --tier "${{ inputs.tier }}"
      shell: bash
